runtime: nodejs18
service: default
# env: flex

# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 10
#   cool_down_period_sec: 180
#   cpu_utilization:
#     target_utilization: 0.5

# env_variables:
#   PORT: 8080
#   DB_USERNAME: your_db_username
#   DB_PASSWORD: your_db_password
#   DB_HOST: your_db_host
#   DB_NAME: your_db_name
#   TOKEN_SECRET_KEY: your_token_secret_key
#   PROJECT_ID: your_project_id
#   BUCKET_NAME: your_bucket_name
